### ISSUE TITLE
Problem in Bode magnitude

### ISSUE THREAD

**Issue by CreatoreDiMacchine** [GalBarkai/asymptotic_bode#1]
Hi, great job! Seems a very useful program! I would use it for my high school students.
However, I have a problem with this script, in fact the asymptotic plotted Bode magnitude is uncorrect. It seems the calculation has an issue.

clear;
close all;
s = tf('s');       
H = 5e8 / ( (s^2+2050*s+100000)*(s+500) );
asymptotic_bode(H);

**Comment by GalBarkai** [comment]
Fixed now, thanks!
